# Generated by Django 2.0.3 on 2018-03-23 18:04

from django.db import migrations, models
import django.db.models.deletion
import token_service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API_key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token_id', models.IntegerField(primary_key=True, serialize=False)),
                ('access_token', token_service.models.EncryptedTextField()),
                ('refresh_token', token_service.models.EncryptedTextField()),
                ('expires', models.DateTimeField()),
                ('provider', models.CharField(max_length=256)),
                ('issuer', models.CharField(max_length=256)),
                ('enabled', models.BooleanField(default=True)),
                ('scopes', models.ManyToManyField(to='token_service.Scope')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=256)),
                ('user_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='token',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='token_service.User'),
        ),
    ]
