# Generated by Django 2.1.1 on 2019-01-15 00:23

from django.db import migrations
import token_service.models


class Migration(migrations.Migration):

    dependencies = [
        ('token_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=token_service.models.EncryptedTextField(default=''),
        ),
    ]
